default_platform(:ios)

platform :ios do
  desc "Build signed build for iOS"
  lane :build_ipa do |options|
    # Create a temporary keychain for the certificates and unlock it
    create_keychain(
      name: "teamcity",
      password: "teamcity",
      default_keychain: false,
      unlock: true,
      timeout: 3600
    )

    # Import the developer's private key
    import_certificate(
      certificate_path: File.absolute_path("tmp/private.p12"),
      certificate_password: options[:certificate_password],
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )

    # Import the developer's signing certificate
    import_certificate(
      certificate_path: File.absolute_path("tmp/signing.cer"),
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )

    # Also import the 6 Apple CA certificates
    import_certificate(
      certificate_path: File.absolute_path("tmp/AppleWWDRCA.cer"),
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )
    import_certificate(
      certificate_path: File.absolute_path("tmp/AppleWWDRCAG2.cer"),
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )
    import_certificate(
      certificate_path: File.absolute_path("tmp/AppleWWDRCAG3.cer"),
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )
    import_certificate(
      certificate_path: File.absolute_path("tmp/AppleWWDRCAG4.cer"),
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )
    import_certificate(
      certificate_path: File.absolute_path("tmp/AppleWWDRCAG5.cer"),
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )
    import_certificate(
      certificate_path: File.absolute_path("tmp/AppleWWDRCAG6.cer"),
      keychain_name: "teamcity",
      keychain_password: "teamcity"
    )

    # Install the developer's provisioning profile
    install_provisioning_profile(
      path: File.absolute_path("tmp/hello-ios.mobileprovision")
    )

    # Update the project and code signing settings
    update_code_signing_settings(
      path: "Hello\ iOS.xcodeproj",
      use_automatic_signing: false,
      team_id: options[:team_id],
      bundle_identifier: options[:bundle_identifier],
      code_sign_identity: options[:code_sign_identity],
      profile_name: options[:provisioning_profile_name],
      targets: "Hello\ iOS"
    )

    increment_version_number(
      version_number: options[:version_number]
    )

    build_app(
      output_name: "build.ipa",
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          options[:bundle_identifier] => options[:provisioning_profile_name],
          "dev.draft.Hello-iOS" => "Kumar Harsh"
        }
      }
    )

  end

  desc "Deploy to TestFlight"
  lane :deploy_to_testflight do |options|
    api_key = app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_filepath: File.absolute_path("tmp/AuthKey.p8"),
      duration: 1200,
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: File.absolute_path("../build.ipa"),
      changelog: options[:changelog],
      first_name: "TeamCity",
      last_name: "CI Server",
      wait_processing_interval: 15,
      localized_build_info: {
        default: {
          whats_new: options[:changelog],
        }
      }
    )
  end

  desc "Build unsigned archive Unity sample project for iOS"
  lane :build_xcarchive do
    build_app(
      export_method: "app-store",
      skip_codesigning: true,
      skip_package_ipa: true
    )
  end

  desc "Run unit tests"
  lane :tests do
#    load_asc_api_key
#    prepare_signing
    run_tests(
      scheme: "Hello iOSTests",
    )
  end

end
